In [20]:
## Installlation
# !pip install pandas



In [19]:
# some imports
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
def max_closing_value(symbol):
    """
    Read the csv file as data frame return data frame
    """
    df = pd.read_csv("data/{}.csv".format(symbol))
    return df["Close"].max()


def calculate_volume_mean_value(symbol):
    df = pd.read_csv("data/{}.csv".format(symbol))
    return df["volume"].mean()


def plot_adjusted_price(symbol):
    df = pd.read_csv("data/{}.csv".format(symbol))
    df["Adj Close"].plot()

def print_max_closing_value():
    for symbol in ['AAPL']:
        print(max_closing_value(symbol))
        

def plot_two_columns(symbol):
    df = pd.read_csv("data/{}.csv")
    ax = df["Open", "Adjusted"].plot(title="Nepse plotting", fontsize=2)
    ax.set_xlabel()
    ax.set_ylabel()
    df["Open", "Adjusted"].show()
    

def join_data_frame(symbol1, symbol2):
    df1 = pd.read_csv("data/{}".format(symbol1), index_cols="Date", parse_dates=True)
    df2 = pd.read_csv("data/{}".format(symbol2), index_cols="Date", parse_dates=True, use_cols=['Date', 'Adj Close'], na_values=['nan'])
    
    # Left join
    df1 = df1.join(df2)
    print(df1)
    
    # drop the nan rows
    df1.dropna()
    

def normalize_data(df):
    """
    Data are normalized to compare the stock with each other, by dividing each value of column with
    starting price
    """
    return df/df.ix[0, :]


## Numpy

In [3]:
import numpy as np
import pandas as pd

In [98]:
# random array of size 100 * 100
np.random.rand(100, 100) * 10 

arr1 = np.ones(5)
arr2 = np.empty(100)
arr3 = np.random.random((100, 100)) # size is 100 x 100



# array shape
print("Array shape is:", arr3.shape, end="\n")

# Array access
print("Row is ", arr3.shape[0])
print("Column is", arr.shape[1])

# Total elements
print("Total number of elements is ", arr3.size)

# Print data type
print("The data type in the array is ", arr3.dtype)
 
# Seed
np.random.seed(324)

# Create an array using random
arr4 = np.random.rand(20, 10)

a = np.random.random((4, 4)) # 4 x 4 matrix with random values

# Numpy array with values 0 to 10 with size 4 x 5 
b = np.random.randint(0, 10, size=(4, 5))
print(b, end="\n")

# Sum the rows 
print(a, end="\n")

# Iterate over rows to compute sum of each columns
print("Sum of all columns: ", a.sum(axis=0), end="\n")
print("Miniumum value of each columns\n", a.min(axis=0), end="\n")
print("Minimum value of each rows", a.min(axis=1), end="\n")

# Iterate over columns to compute the sum of each row using axis = 1
print("Sum of all rows is: ", a.sum(axis=1), end="\n")

# Statistics operation
print("Sum: ", arr4.sum(), end="\n")
print("Mean: ", arr4.mean(), end="\n")
print("Std: ", arr4.std(), end="\n")
print("Minimum value", a.min(), end="\n")
print("Maximum value", a.max(), end="\n")



Array shape is: (100, 100)
Row is  100
Column is 20
Total number of elements is  10000
The data type in the array is  float64
[[5 8 4 8 6]
 [9 8 6 6 0]
 [9 8 2 6 7]
 [0 2 8 8 7]]
[[0.32279788 0.80382292 0.7972804  0.69202906]
 [0.86098762 0.43641893 0.80837458 0.12460679]
 [0.08893122 0.0987576  0.56561349 0.89674904]
 [0.66946672 0.06993603 0.0395293  0.13210896]]
Sum of all columns:  [1.94218344 1.40893547 2.21079778 1.84549386]
Miniumum value of each columns
 [0.08893122 0.06993603 0.0395293  0.12460679]
Minimum value of each rows [0.32279788 0.12460679 0.08893122 0.0395293 ]
Sum of all rows is:  [2.61593026 2.23038793 1.65005134 0.91104102]
Sum:  89.97579194749787
Mean:  0.4498789597374893
Std:  0.2831382357840637
Minimum value 0.03952930324531423
Maximum value 0.8967490396727675
