In [20]:
## Installlation
# !pip install pandas



In [19]:
# some imports
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
def max_closing_value(symbol):
    """
    Read the csv file as data frame return data frame
    """
    df = pd.read_csv("data/{}.csv".format(symbol))
    return df["Close"].max()


def calculate_volume_mean_value(symbol):
    df = pd.read_csv("data/{}.csv".format(symbol))
    return df["volume"].mean()


def plot_adjusted_price(symbol):
    df = pd.read_csv("data/{}.csv".format(symbol))
    df["Adj Close"].plot()

def print_max_closing_value():
    for symbol in ['AAPL']:
        print(max_closing_value(symbol))
        

def plot_two_columns(symbol):
    df = pd.read_csv("data/{}.csv")
    ax = df["Open", "Adjusted"].plot(title="Nepse plotting", fontsize=2)
    ax.set_xlabel()
    ax.set_ylabel()
    df["Open", "Adjusted"].show()
    

def join_data_frame(symbol1, symbol2):
    df1 = pd.read_csv("data/{}".format(symbol1), index_cols="Date", parse_dates=True)
    df2 = pd.read_csv("data/{}".format(symbol2), index_cols="Date", parse_dates=True, use_cols=['Date', 'Adj Close'], na_values=['nan'])
    
    # Left join
    df1 = df1.join(df2)
    print(df1)
    
    # drop the nan rows
    df1.dropna()
    

def normalize_data(df):
    """
    Data are normalized to compare the stock with each other, by dividing each value of column with
    starting price
    """
    return df/df.ix[0, :]


## Numpy

In [3]:
import numpy as np
import pandas as pd

In [101]:
# random array of size 100 * 100
np.random.rand(100, 100) * 10 

arr1 = np.ones(5)
arr2 = np.empty(100)
arr3 = np.random.random((100, 100)) # size is 100 x 100



# array shape
print("Array shape is:", arr3.shape, end="\n")

# Array access
print("Row is ", arr3.shape[0])
print("Column is", arr.shape[1])

# Total elements
print("Total number of elements is ", arr3.size)

# Print data type
print("The data type in the array is ", arr3.dtype)
 
# Seed
np.random.seed(324)

# Create an array using random
arr4 = np.random.rand(20, 10)

a = np.random.random((4, 4)) # 4 x 4 matrix with random values

# Numpy array with values 0 to 10 with size 4 x 5 
b = np.random.randint(0, 10, size=(4, 5))
print(b, end="\n")

# Sum the rows 
print(a, end="\n")

# Iterate over rows to compute sum of each columns
print("Sum of all columns: ", a.sum(axis=0), end="\n")
print("Miniumum value of each columns\n", a.min(axis=0), end="\n")
print("Minimum value of each rows", a.min(axis=1), end="\n")

# Iterate over columns to compute the sum of each row using axis = 1
print("Sum of all rows is: ", a.sum(axis=1), end="\n")

# Statistics operation
print("Sum: ", arr4.sum(), end="\n")
print("Mean: ", arr4.mean(), end="\n")
print("Std: ", arr4.std(), end="\n")
print("Minimum value", a.min(), end="\n")
print("Maximum value", a.max(), end="\n")

def return_index_of_max_values_of_each_columns(arr2d):
    '''
    Return the index value which contains max value in each column
    See: http://docs.scipy.org/doc/numpy/reference/routines.sort.html

    '''
    return arr2d.argmax(axis=0)


arr_data = np.random.randint(2,100, size=(500,3)) #500x 3 array 

print("The index that hold max value in each columns ", return_index_of_max_values_of_each_columns(arr_data))



Array shape is: (100, 100)
Row is  100
Column is 20
Total number of elements is  10000
The data type in the array is  float64
[[5 8 4 8 6]
 [9 8 6 6 0]
 [9 8 2 6 7]
 [0 2 8 8 7]]
[[0.32279788 0.80382292 0.7972804  0.69202906]
 [0.86098762 0.43641893 0.80837458 0.12460679]
 [0.08893122 0.0987576  0.56561349 0.89674904]
 [0.66946672 0.06993603 0.0395293  0.13210896]]
Sum of all columns:  [1.94218344 1.40893547 2.21079778 1.84549386]
Miniumum value of each columns
 [0.08893122 0.06993603 0.0395293  0.12460679]
Minimum value of each rows [0.32279788 0.12460679 0.08893122 0.0395293 ]
Sum of all rows is:  [2.61593026 2.23038793 1.65005134 0.91104102]
Sum:  89.97579194749787
Mean:  0.4498789597374893
Std:  0.2831382357840637
Minimum value 0.03952930324531423
Maximum value 0.8967490396727675
The index that hold max value in each columns  [ 9  6 74]


## Timing functions

In [111]:
import time
t1 = time.time()
arr = np.random.randint(2, 200, size=(9000, 9000)) # 9000 x 9000 matrix with 2, 200 random values
arr = arr - (0.12)
t2 = time.time()
print("Total time consumed ", t2 - t1)
print(arr)

Total time consumed  1.3109979629516602
[[142.88  97.88 164.88 ... 185.88 164.88  83.88]
 [195.88  15.88  56.88 ...  22.88 150.88  96.88]
 [141.88  51.88  24.88 ... 185.88 144.88 187.88]
 ...
 [129.88  41.88  69.88 ...   2.88 124.88 186.88]
 [ 74.88  89.88 104.88 ... 133.88  84.88 184.88]
 [188.88 179.88  47.88 ...   7.88  64.88 159.88]]


# Numpy indexing

In [136]:
a = np.random.rand(4, 2)
indices = np.array([1,2,2,1])

# Access data based on indices
k = a[indices]
print("Array with elements indices")
print(k)
print("*" * 85)

# Calculate the mean
mean = a.mean()

# masking 
arrltmean = a[a < mean]
arrgtmean = a[a > mean]

print("Array Elements less than mean with size {} is {}".format(arrltmean.size, arrltmean))

print("*" * 85)
print("Array Elements less than mean with size {} is {}".format(arrgtmean.size, arrgtmean))




print("*" * 85)
print("Original array with size {} is {}".format(a.size, a))



Array with elements indices
[[0.83416687 0.716978  ]
 [0.67602828 0.17067108]
 [0.67602828 0.17067108]
 [0.83416687 0.716978  ]]
*************************************************************************************
Array Elements less than mean with size 4 is [0.41566727 0.46883046 0.17067108 0.02461377]
*************************************************************************************
Array Elements less than mean with size 4 is [0.83416687 0.716978   0.67602828 0.78718692]
*************************************************************************************
Original array with size 8 is [[0.41566727 0.46883046]
 [0.83416687 0.716978  ]
 [0.67602828 0.17067108]
 [0.78718692 0.02461377]]


# NumPy Arithmetic operation

In [148]:
a = np.random.randint(12, 13, size=(4,2))
# Scalar multiplication arr * 2
print("Scalar Multiplication of  array with size {} is {}".format(a.size, a * 2))

# Addition 
b = np.random.randint(22,33, size=(4, 2))
print("Addition of  array with size {} is {}".format(a.size, a + b))

# Subtraction 
print("Subtraction of  array with size {} is {}".format(a.size, a - b))

# Division 
print("Division of  array with size {} is {}".format(a.size, a / b))

# matrix multiplication
matrix_mul = np.dot(np.array([1,23]), np.array([2,2]))
print(matrix_mul)




Scalar Multiplication of  array with size 8 is [[24 24]
 [24 24]
 [24 24]
 [24 24]]
Addition of  array with size 8 is [[40 44]
 [38 44]
 [36 39]
 [42 40]]
Subtraction of  array with size 8 is [[-16 -20]
 [-14 -20]
 [-12 -15]
 [-18 -16]]
Division of  array with size 8 is [[0.42857143 0.375     ]
 [0.46153846 0.375     ]
 [0.5        0.44444444]
 [0.4        0.42857143]]
48


## Some terms regarding statistics
- Global statistics include `mean, median, mode, sum, std, variance`
- Rolling statistics: `rolling_mean, rolling_std`, Rolling statistics between in windows such as 20 Days
- Bollinger Band: A way of quantifying how far stock price has deviated from some norm.

In [169]:
from pathlib import Path
import pandas as pd
csv_path = Path("C:\\Users\\user\\Documents\\Downloads\\Today's Price _2023-02-01.csv")
df = pd.read_csv(csv_path)





AttributeError: module 'pandas' has no attribute 'to_sql'